spring:
  application:
    name: stp-client
  profiles:
    active: dev
server:
  port: 7003
  servlet:
    context-path: /stp-client
  error:
    include-message: always
logging:
  level:
    com.noh.stpclient.config.interceptor: DEBUG
